[phases.setup]
nixPkgs = ["nodejs_22", "ffmpeg"]

[phases.install]
cmds = ["npm ci", "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp", "chmod a+rx /usr/local/bin/yt-dlp"]

[start]
cmd = "node index.js"