[phases.setup]
nixPkgs = ["nodejs_22", "ffmpeg", "python3"]

[phases.install]
cmds = [
  "npm ci",
  "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp",
  "chmod a+rx /usr/local/bin/yt-dlp",
  "mkdir -p /root/.yt-dlp/plugins",
  "curl -L https://github.com/coletdjnz/yt-dlp-get-pot/releases/latest/download/yt-dlp-get-pot.zip -o /root/.yt-dlp/plugins/yt-dlp-get-pot.zip"
]

[start]
cmd = "node index.js"